import { Question } from "@/types";

export const SAMPLE_QUESTIONS: Question[] = [
  {
    id: "q_1",
    title: "JavaScript Closures",
    slug: "javascript-closures",
    question: "What will the following code output?\n\nfor (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 1000);\n}",
    codeSnippet: "for (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 1000);\n}",
    options: [
      "0 1 2",
      "3 3 3",
      "undefined undefined undefined",
      "0 0 0"
    ],
    correctAnswer: 1,
    explanation: "Because 'var' is function-scoped, the closure captures the same variable 'i'. By the time the setTimeout callbacks run, the loop has completed and i equals 3. All three callbacks print 3.",
    difficulty: "EASY",
    category: "JavaScript",
    solveCount: 18420,
    attemptCount: 24560,
  },
  {
    id: "q_2",
    title: "Python List Mutation",
    slug: "python-list-mutation",
    question: "What is the output of this Python code?\n\na = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)",
    codeSnippet: "a = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)",
    options: [
      "[1, 2, 3]",
      "[1, 2, 3, 4]",
      "[4, 1, 2, 3]",
      "Error"
    ],
    correctAnswer: 1,
    explanation: "In Python, 'b = a' doesn't copy the list — it creates a reference to the same list object. So when b.append(4) is called, it modifies the same list that 'a' points to. Both a and b reference [1, 2, 3, 4].",
    difficulty: "EASY",
    category: "Python",
    solveCount: 21300,
    attemptCount: 27800,
  },
  {
    id: "q_3",
    title: "HTTP Status Codes",
    slug: "http-status-codes",
    question: "Which HTTP status code indicates that the server understood the request but refuses to authorize it?",
    options: [
      "401 Unauthorized",
      "403 Forbidden",
      "404 Not Found",
      "405 Method Not Allowed"
    ],
    correctAnswer: 1,
    explanation: "403 Forbidden means the server understood the request but refuses to authorize it. 401 means the client must authenticate itself. The key difference: 401 = 'who are you?', 403 = 'I know who you are, but you can't do this.'",
    difficulty: "EASY",
    category: "Web Development",
    solveCount: 25100,
    attemptCount: 30200,
  },
  {
    id: "q_4",
    title: "Big O Complexity",
    slug: "big-o-complexity",
    question: "What is the time complexity of searching for an element in a balanced Binary Search Tree (BST) with n nodes?",
    options: [
      "O(1)",
      "O(n)",
      "O(log n)",
      "O(n log n)"
    ],
    correctAnswer: 2,
    explanation: "In a balanced BST, each comparison eliminates half of the remaining nodes, similar to binary search. This gives us O(log n) time complexity. An unbalanced BST could degrade to O(n) in the worst case.",
    difficulty: "MEDIUM",
    category: "Data Structures",
    solveCount: 14200,
    attemptCount: 21500,
  },
  {
    id: "q_5",
    title: "React useEffect Cleanup",
    slug: "react-useeffect-cleanup",
    question: "When does the cleanup function returned from useEffect run?",
    codeSnippet: "useEffect(() => {\n  const sub = subscribe();\n  return () => sub.unsubscribe();\n}, [channel]);",
    options: [
      "Only when the component mounts",
      "Only when the component unmounts",
      "Before the effect re-runs and when the component unmounts",
      "After every render"
    ],
    correctAnswer: 2,
    explanation: "The cleanup function runs in two cases: (1) before the effect re-runs due to dependency changes, and (2) when the component unmounts. This prevents memory leaks and stale subscriptions.",
    difficulty: "MEDIUM",
    category: "React",
    solveCount: 11800,
    attemptCount: 19400,
  },
  {
    id: "q_6",
    title: "SQL JOIN Types",
    slug: "sql-join-types",
    question: "You have tables 'users' (5 rows) and 'orders' (3 rows, each linked to a user). How many rows does a LEFT JOIN of users to orders return?",
    options: [
      "3 rows",
      "5 rows",
      "8 rows",
      "15 rows"
    ],
    correctAnswer: 1,
    explanation: "A LEFT JOIN returns all rows from the left table (users = 5) with matching rows from the right table. Users without orders get NULL values for order columns. Since 3 users have orders and 2 don't, you get 5 rows total (3 matched + 2 with NULLs).",
    difficulty: "MEDIUM",
    category: "Databases",
    solveCount: 9800,
    attemptCount: 16700,
  },
  {
    id: "q_7",
    title: "TypeScript Generics",
    slug: "typescript-generics",
    question: "What TypeScript type does the following function return?\n\nfunction identity<T>(arg: T): T {\n  return arg;\n}\nconst result = identity('hello');",
    codeSnippet: "function identity<T>(arg: T): T {\n  return arg;\n}\nconst result = identity('hello');",
    options: [
      "any",
      "unknown",
      "string",
      "T"
    ],
    correctAnswer: 2,
    explanation: "TypeScript infers the generic type parameter T from the argument. Since 'hello' is a string, T is inferred as string (specifically the literal type 'hello'). The return type is therefore string.",
    difficulty: "MEDIUM",
    category: "TypeScript",
    solveCount: 8900,
    attemptCount: 14300,
  },
  {
    id: "q_8",
    title: "Docker Layers",
    slug: "docker-layers",
    question: "In a Dockerfile, which instruction does NOT create a new layer?",
    options: [
      "RUN apt-get update",
      "COPY . /app",
      "ENV NODE_ENV=production",
      "ADD package.json /app/"
    ],
    correctAnswer: 2,
    explanation: "ENV, LABEL, EXPOSE, CMD, and ENTRYPOINT create metadata changes but don't add filesystem layers. RUN, COPY, and ADD create new layers because they modify the filesystem. ENV only sets an environment variable.",
    difficulty: "HARD",
    category: "DevOps",
    solveCount: 5400,
    attemptCount: 12800,
  },
  {
    id: "q_9",
    title: "System Design: CAP Theorem",
    slug: "cap-theorem",
    question: "According to the CAP theorem, a distributed system can guarantee at most two of three properties. Which combination is NOT possible during a network partition?",
    options: [
      "Consistency + Availability",
      "Consistency + Partition Tolerance",
      "Availability + Partition Tolerance",
      "All three simultaneously"
    ],
    correctAnswer: 0,
    explanation: "During a network partition, you must choose between Consistency and Availability. You can't have both — either you reject requests (lose Availability) to maintain Consistency, or you serve potentially stale data (lose Consistency) to maintain Availability. CP and AP systems exist, but CA is impossible during partitions.",
    difficulty: "HARD",
    category: "System Design",
    solveCount: 4200,
    attemptCount: 11500,
  },
  {
    id: "q_10",
    title: "CSS Specificity",
    slug: "css-specificity",
    question: "Which CSS selector has the HIGHEST specificity?",
    options: [
      "#header .nav a",
      ".header .nav .link",
      "header nav a.active",
      "#header a"
    ],
    correctAnswer: 0,
    explanation: "Specificity is calculated as (IDs, Classes, Elements). '#header .nav a' = (1,1,1). '.header .nav .link' = (0,3,0). 'header nav a.active' = (0,1,3). '#header a' = (1,0,1). The first selector wins with the highest ID count and a class.",
    difficulty: "EASY",
    category: "CSS",
    solveCount: 16700,
    attemptCount: 22100,
  },
  {
    id: "q_11",
    title: "Git Rebase vs Merge",
    slug: "git-rebase-vs-merge",
    question: "What is the key difference between 'git rebase' and 'git merge'?",
    options: [
      "Rebase is faster than merge",
      "Rebase rewrites commit history, merge creates a merge commit",
      "Merge can cause conflicts, rebase cannot",
      "Rebase only works on remote branches"
    ],
    correctAnswer: 1,
    explanation: "Git rebase replays commits from one branch on top of another, creating new commits and rewriting history for a linear timeline. Git merge creates a new merge commit that joins two branches, preserving the original history. Both can cause conflicts.",
    difficulty: "EASY",
    category: "Git",
    solveCount: 19500,
    attemptCount: 25800,
  },
  {
    id: "q_12",
    title: "Concurrency: Race Condition",
    slug: "race-condition",
    question: "Two threads simultaneously execute 'counter++' where counter = 0. The operation involves read, increment, and write steps. What are the possible final values of counter?",
    options: [
      "Always 2",
      "1 or 2",
      "0, 1, or 2",
      "Only 1"
    ],
    correctAnswer: 1,
    explanation: "If both threads read 0, both increment to 1, and both write 1, the result is 1 (race condition). If the operations are properly sequenced, the result is 2. The value 0 is not possible because at least one write will succeed. So possible values are 1 or 2.",
    difficulty: "HARD",
    category: "Concurrency",
    solveCount: 3800,
    attemptCount: 10200,
  },
  {
    id: "q_13",
    title: "Kubernetes Pods",
    slug: "kubernetes-pods",
    question: "In Kubernetes, what happens when a container inside a Pod crashes?",
    options: [
      "The entire Pod is terminated and never restarted",
      "The kubelet restarts the container with exponential backoff",
      "A new Pod is created on a different node",
      "The cluster shuts down for safety"
    ],
    correctAnswer: 1,
    explanation: "When a container crashes, the kubelet automatically restarts it with an exponential backoff delay (10s, 20s, 40s... up to 5 minutes). This is the default restartPolicy: Always. The Pod itself stays on the same node — only the container is restarted.",
    difficulty: "HARD",
    category: "DevOps",
    solveCount: 4100,
    attemptCount: 9800,
  },
  {
    id: "q_14",
    title: "JavaScript Event Loop",
    slug: "js-event-loop",
    question: "What is the output order?\n\nconsole.log('1');\nsetTimeout(() => console.log('2'), 0);\nPromise.resolve().then(() => console.log('3'));\nconsole.log('4');",
    codeSnippet: "console.log('1');\nsetTimeout(() => console.log('2'), 0);\nPromise.resolve().then(() => console.log('3'));\nconsole.log('4');",
    options: [
      "1, 2, 3, 4",
      "1, 4, 2, 3",
      "1, 4, 3, 2",
      "1, 3, 4, 2"
    ],
    correctAnswer: 2,
    explanation: "Synchronous code runs first: '1' then '4'. Microtasks (Promise.then) have priority over macrotasks (setTimeout). So '3' runs next, then '2'. Output: 1, 4, 3, 2.",
    difficulty: "MEDIUM",
    category: "JavaScript",
    solveCount: 12100,
    attemptCount: 18900,
  },
  {
    id: "q_15",
    title: "REST vs GraphQL",
    slug: "rest-vs-graphql",
    question: "Which problem does GraphQL solve that REST APIs commonly face?",
    options: [
      "GraphQL is faster because it uses WebSockets",
      "GraphQL eliminates over-fetching and under-fetching of data",
      "GraphQL doesn't require a server",
      "GraphQL automatically caches all responses"
    ],
    correctAnswer: 1,
    explanation: "GraphQL lets clients request exactly the data they need in a single query, solving REST's over-fetching (getting unnecessary fields) and under-fetching (needing multiple endpoints). It still uses HTTP, requires a server, and doesn't auto-cache.",
    difficulty: "EASY",
    category: "Web Development",
    solveCount: 17200,
    attemptCount: 22600,
  },
];
