import { Question } from "@/types";

export const SAMPLE_QUESTIONS: Question[] = [
  {
    id: "q_1",
    title: "JavaScript Closures",
    slug: "javascript-closures",
    question: "What will the following code output?\n\nfor (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 1000);\n}",
    codeSnippet: "for (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 1000);\n}",
    options: [
      "0 1 2",
      "3 3 3",
      "undefined undefined undefined",
      "0 0 0"
    ],
    correctAnswer: 1,
    explanation: "Because 'var' is function-scoped, the closure captures the same variable 'i'. By the time the setTimeout callbacks run, the loop has completed and i equals 3. All three callbacks print 3.",
    difficulty: "EASY",
    category: "JavaScript",
    solveCount: 18420,
    attemptCount: 24560,
  },
  {
    id: "q_2",
    title: "Python List Mutation",
    slug: "python-list-mutation",
    question: "What is the output of this Python code?\n\na = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)",
    codeSnippet: "a = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)",
    options: [
      "[1, 2, 3]",
      "[1, 2, 3, 4]",
      "[4, 1, 2, 3]",
      "Error"
    ],
    correctAnswer: 1,
    explanation: "In Python, 'b = a' doesn't copy the list — it creates a reference to the same list object. So when b.append(4) is called, it modifies the same list that 'a' points to. Both a and b reference [1, 2, 3, 4].",
    difficulty: "EASY",
    category: "Python",
    solveCount: 21300,
    attemptCount: 27800,
  },
  {
    id: "q_3",
    title: "HTTP Status Codes",
    slug: "http-status-codes",
    question: "Which HTTP status code indicates that the server understood the request but refuses to authorize it?",
    options: [
      "401 Unauthorized",
      "403 Forbidden",
      "404 Not Found",
      "405 Method Not Allowed"
    ],
    correctAnswer: 1,
    explanation: "403 Forbidden means the server understood the request but refuses to authorize it. 401 means the client must authenticate itself. The key difference: 401 = 'who are you?', 403 = 'I know who you are, but you can't do this.'",
    difficulty: "EASY",
    category: "Web Development",
    solveCount: 25100,
    attemptCount: 30200,
  },
  {
    id: "q_4",
    title: "Big O Complexity",
    slug: "big-o-complexity",
    question: "What is the time complexity of searching for an element in a balanced Binary Search Tree (BST) with n nodes?",
    options: [
      "O(1)",
      "O(n)",
      "O(log n)",
      "O(n log n)"
    ],
    correctAnswer: 2,
    explanation: "In a balanced BST, each comparison eliminates half of the remaining nodes, similar to binary search. This gives us O(log n) time complexity. An unbalanced BST could degrade to O(n) in the worst case.",
    difficulty: "MEDIUM",
    category: "Data Structures",
    solveCount: 14200,
    attemptCount: 21500,
  },
  {
    id: "q_5",
    title: "React useEffect Cleanup",
    slug: "react-useeffect-cleanup",
    question: "When does the cleanup function returned from useEffect run?",
    codeSnippet: "useEffect(() => {\n  const sub = subscribe();\n  return () => sub.unsubscribe();\n}, [channel]);",
    options: [
      "Only when the component mounts",
      "Only when the component unmounts",
      "Before the effect re-runs and when the component unmounts",
      "After every render"
    ],
    correctAnswer: 2,
    explanation: "The cleanup function runs in two cases: (1) before the effect re-runs due to dependency changes, and (2) when the component unmounts. This prevents memory leaks and stale subscriptions.",
    difficulty: "MEDIUM",
    category: "React",
    solveCount: 11800,
    attemptCount: 19400,
  },
  {
    id: "q_6",
    title: "SQL JOIN Types",
    slug: "sql-join-types",
    question: "You have tables 'users' (5 rows) and 'orders' (3 rows, each linked to a user). How many rows does a LEFT JOIN of users to orders return?",
    options: [
      "3 rows",
      "5 rows",
      "8 rows",
      "15 rows"
    ],
    correctAnswer: 1,
    explanation: "A LEFT JOIN returns all rows from the left table (users = 5) with matching rows from the right table. Users without orders get NULL values for order columns. Since 3 users have orders and 2 don't, you get 5 rows total (3 matched + 2 with NULLs).",
    difficulty: "MEDIUM",
    category: "Databases",
    solveCount: 9800,
    attemptCount: 16700,
  },
  {
    id: "q_7",
    title: "TypeScript Generics",
    slug: "typescript-generics",
    question: "What TypeScript type does the following function return?\n\nfunction identity<T>(arg: T): T {\n  return arg;\n}\nconst result = identity('hello');",
    codeSnippet: "function identity<T>(arg: T): T {\n  return arg;\n}\nconst result = identity('hello');",
    options: [
      "any",
      "unknown",
      "string",
      "T"
    ],
    correctAnswer: 2,
    explanation: "TypeScript infers the generic type parameter T from the argument. Since 'hello' is a string, T is inferred as string (specifically the literal type 'hello'). The return type is therefore string.",
    difficulty: "MEDIUM",
    category: "TypeScript",
    solveCount: 8900,
    attemptCount: 14300,
  },
  {
    id: "q_8",
    title: "Docker Layers",
    slug: "docker-layers",
    question: "In a Dockerfile, which instruction does NOT create a new layer?",
    options: [
      "RUN apt-get update",
      "COPY . /app",
      "ENV NODE_ENV=production",
      "ADD package.json /app/"
    ],
    correctAnswer: 2,
    explanation: "ENV, LABEL, EXPOSE, CMD, and ENTRYPOINT create metadata changes but don't add filesystem layers. RUN, COPY, and ADD create new layers because they modify the filesystem. ENV only sets an environment variable.",
    difficulty: "HARD",
    category: "DevOps",
    solveCount: 5400,
    attemptCount: 12800,
  },
  {
    id: "q_9",
    title: "System Design: CAP Theorem",
    slug: "cap-theorem",
    question: "According to the CAP theorem, a distributed system can guarantee at most two of three properties. Which combination is NOT possible during a network partition?",
    options: [
      "Consistency + Availability",
      "Consistency + Partition Tolerance",
      "Availability + Partition Tolerance",
      "All three simultaneously"
    ],
    correctAnswer: 0,
    explanation: "During a network partition, you must choose between Consistency and Availability. You can't have both — either you reject requests (lose Availability) to maintain Consistency, or you serve potentially stale data (lose Consistency) to maintain Availability. CP and AP systems exist, but CA is impossible during partitions.",
    difficulty: "HARD",
    category: "System Design",
    solveCount: 4200,
    attemptCount: 11500,
  },
  {
    id: "q_10",
    title: "CSS Specificity",
    slug: "css-specificity",
    question: "Which CSS selector has the HIGHEST specificity?",
    options: [
      "#header .nav a",
      ".header .nav .link",
      "header nav a.active",
      "#header a"
    ],
    correctAnswer: 0,
    explanation: "Specificity is calculated as (IDs, Classes, Elements). '#header .nav a' = (1,1,1). '.header .nav .link' = (0,3,0). 'header nav a.active' = (0,1,3). '#header a' = (1,0,1). The first selector wins with the highest ID count and a class.",
    difficulty: "EASY",
    category: "CSS",
    solveCount: 16700,
    attemptCount: 22100,
  },
  {
    id: "q_11",
    title: "Git Rebase vs Merge",
    slug: "git-rebase-vs-merge",
    question: "What is the key difference between 'git rebase' and 'git merge'?",
    options: [
      "Rebase is faster than merge",
      "Rebase rewrites commit history, merge creates a merge commit",
      "Merge can cause conflicts, rebase cannot",
      "Rebase only works on remote branches"
    ],
    correctAnswer: 1,
    explanation: "Git rebase replays commits from one branch on top of another, creating new commits and rewriting history for a linear timeline. Git merge creates a new merge commit that joins two branches, preserving the original history. Both can cause conflicts.",
    difficulty: "EASY",
    category: "Git",
    solveCount: 19500,
    attemptCount: 25800,
  },
  {
    id: "q_12",
    title: "Concurrency: Race Condition",
    slug: "race-condition",
    question: "Two threads simultaneously execute 'counter++' where counter = 0. The operation involves read, increment, and write steps. What are the possible final values of counter?",
    options: [
      "Always 2",
      "1 or 2",
      "0, 1, or 2",
      "Only 1"
    ],
    correctAnswer: 1,
    explanation: "If both threads read 0, both increment to 1, and both write 1, the result is 1 (race condition). If the operations are properly sequenced, the result is 2. The value 0 is not possible because at least one write will succeed. So possible values are 1 or 2.",
    difficulty: "HARD",
    category: "Concurrency",
    solveCount: 3800,
    attemptCount: 10200,
  },
  {
    id: "q_13",
    title: "Kubernetes Pods",
    slug: "kubernetes-pods",
    question: "In Kubernetes, what happens when a container inside a Pod crashes?",
    options: [
      "The entire Pod is terminated and never restarted",
      "The kubelet restarts the container with exponential backoff",
      "A new Pod is created on a different node",
      "The cluster shuts down for safety"
    ],
    correctAnswer: 1,
    explanation: "When a container crashes, the kubelet automatically restarts it with an exponential backoff delay (10s, 20s, 40s... up to 5 minutes). This is the default restartPolicy: Always. The Pod itself stays on the same node — only the container is restarted.",
    difficulty: "HARD",
    category: "DevOps",
    solveCount: 4100,
    attemptCount: 9800,
  },
  {
    id: "q_14",
    title: "JavaScript Event Loop",
    slug: "js-event-loop",
    question: "What is the output order?\n\nconsole.log('1');\nsetTimeout(() => console.log('2'), 0);\nPromise.resolve().then(() => console.log('3'));\nconsole.log('4');",
    codeSnippet: "console.log('1');\nsetTimeout(() => console.log('2'), 0);\nPromise.resolve().then(() => console.log('3'));\nconsole.log('4');",
    options: [
      "1, 2, 3, 4",
      "1, 4, 2, 3",
      "1, 4, 3, 2",
      "1, 3, 4, 2"
    ],
    correctAnswer: 2,
    explanation: "Synchronous code runs first: '1' then '4'. Microtasks (Promise.then) have priority over macrotasks (setTimeout). So '3' runs next, then '2'. Output: 1, 4, 3, 2.",
    difficulty: "MEDIUM",
    category: "JavaScript",
    solveCount: 12100,
    attemptCount: 18900,
  },
  {
    id: "q_15",
    title: "REST vs GraphQL",
    slug: "rest-vs-graphql",
    question: "Which problem does GraphQL solve that REST APIs commonly face?",
    options: [
      "GraphQL is faster because it uses WebSockets",
      "GraphQL eliminates over-fetching and under-fetching of data",
      "GraphQL doesn't require a server",
      "GraphQL automatically caches all responses"
    ],
    correctAnswer: 1,
    explanation: "GraphQL lets clients request exactly the data they need in a single query, solving REST's over-fetching (getting unnecessary fields) and under-fetching (needing multiple endpoints). It still uses HTTP, requires a server, and doesn't auto-cache.",
    difficulty: "EASY",
    category: "Web Development",
    solveCount: 17200,
    attemptCount: 22600,
  },
  {
    id: "q_16",
    title: "JavaScript Prototypal Inheritance",
    slug: "js-prototypal-inheritance",
    question: "What does Object.create(null) return?",
    options: [
      "An empty object with Object.prototype",
      "null",
      "An object with no prototype chain",
      "Throws a TypeError"
    ],
    correctAnswer: 2,
    explanation: "Object.create(null) creates a truly empty object with no prototype. It has no inherited methods like toString() or hasOwnProperty(). This is sometimes used for creating clean dictionary-like objects.",
    difficulty: "MEDIUM",
    category: "JavaScript",
    solveCount: 8700,
    attemptCount: 14200,
  },
  {
    id: "q_17",
    title: "Python Decorators",
    slug: "python-decorators",
    question: "What does the @staticmethod decorator do in Python?",
    options: [
      "Makes the method run faster",
      "Binds the method to the class instance",
      "Defines a method that doesn't receive self or cls as first argument",
      "Makes the method private"
    ],
    correctAnswer: 2,
    explanation: "@staticmethod defines a method that belongs to the class namespace but doesn't receive the instance (self) or class (cls) as the first argument. It behaves like a regular function that happens to live inside a class.",
    difficulty: "EASY",
    category: "Python",
    solveCount: 19800,
    attemptCount: 24100,
  },
  {
    id: "q_18",
    title: "Hash Table Collision",
    slug: "hash-table-collision",
    question: "What is the average time complexity of searching in a hash table with good hash function?",
    options: [
      "O(n)",
      "O(log n)",
      "O(1)",
      "O(n log n)"
    ],
    correctAnswer: 2,
    explanation: "With a good hash function and proper load factor, hash table lookups average O(1). The hash function maps the key directly to an index. Worst case is O(n) when all keys collide to the same bucket, but this is rare with a good hash function.",
    difficulty: "EASY",
    category: "Data Structures",
    solveCount: 22100,
    attemptCount: 26500,
  },
  {
    id: "q_19",
    title: "React Virtual DOM",
    slug: "react-virtual-dom",
    question: "Why does React use a Virtual DOM instead of directly manipulating the real DOM?",
    options: [
      "The Virtual DOM is stored on the server",
      "Batching and diffing changes is faster than direct DOM manipulation",
      "The real DOM doesn't support JavaScript",
      "The Virtual DOM prevents all re-renders"
    ],
    correctAnswer: 1,
    explanation: "React's Virtual DOM allows it to batch multiple state changes, compute the minimal set of DOM updates via a diffing algorithm, and apply them in one go. Direct DOM manipulation for every change would cause excessive reflows and repaints.",
    difficulty: "EASY",
    category: "React",
    solveCount: 20400,
    attemptCount: 25700,
  },
  {
    id: "q_20",
    title: "SQL Indexing",
    slug: "sql-indexing",
    question: "What is the primary disadvantage of adding too many indexes to a database table?",
    options: [
      "SELECT queries become slower",
      "The table can no longer store data",
      "INSERT, UPDATE, and DELETE operations become slower",
      "Indexes don't work on large tables"
    ],
    correctAnswer: 2,
    explanation: "Each index must be updated whenever data is inserted, updated, or deleted. More indexes means more overhead on write operations. While indexes speed up reads, excessive indexing degrades write performance and increases storage usage.",
    difficulty: "MEDIUM",
    category: "Databases",
    solveCount: 10500,
    attemptCount: 16200,
  },
  {
    id: "q_21",
    title: "TypeScript Utility Types",
    slug: "typescript-utility-types",
    question: "What does Partial<T> do in TypeScript?",
    codeSnippet: "interface User {\n  name: string;\n  age: number;\n}\ntype OptionalUser = Partial<User>;",
    options: [
      "Makes all properties required",
      "Makes all properties optional",
      "Removes all properties",
      "Makes all properties readonly"
    ],
    correctAnswer: 1,
    explanation: "Partial<T> constructs a type with all properties of T set to optional. So Partial<User> becomes { name?: string; age?: number; }. This is useful for update functions where you only want to pass changed fields.",
    difficulty: "EASY",
    category: "TypeScript",
    solveCount: 16300,
    attemptCount: 20100,
  },
  {
    id: "q_22",
    title: "CSS Flexbox",
    slug: "css-flexbox",
    question: "What does 'justify-content: space-between' do in a flex container?",
    options: [
      "Centers all items",
      "Distributes items with equal space between them, first and last items touch edges",
      "Adds space before the first item only",
      "Wraps items to the next line"
    ],
    correctAnswer: 1,
    explanation: "justify-content: space-between distributes flex items so the first item is at the start, the last item is at the end, and remaining items have equal space between them. No space is added before the first or after the last item.",
    difficulty: "EASY",
    category: "CSS",
    solveCount: 23400,
    attemptCount: 27200,
  },
  {
    id: "q_23",
    title: "Git Cherry-Pick",
    slug: "git-cherry-pick",
    question: "What does 'git cherry-pick <commit>' do?",
    options: [
      "Deletes the specified commit",
      "Applies the changes from a specific commit onto the current branch",
      "Reverts the specified commit",
      "Merges two branches together"
    ],
    correctAnswer: 1,
    explanation: "git cherry-pick takes a specific commit from one branch and applies it to your current branch as a new commit. It's useful when you want to bring a specific fix or feature from another branch without merging the entire branch.",
    difficulty: "MEDIUM",
    category: "Git",
    solveCount: 11200,
    attemptCount: 17800,
  },
  {
    id: "q_24",
    title: "JavaScript Promises",
    slug: "js-promises",
    question: "What does Promise.all() return if one of the promises rejects?",
    codeSnippet: "Promise.all([\n  Promise.resolve(1),\n  Promise.reject('error'),\n  Promise.resolve(3)\n]);",
    options: [
      "[1, 'error', 3]",
      "[1, undefined, 3]",
      "Rejects with 'error'",
      "Resolves with [1, 3]"
    ],
    correctAnswer: 2,
    explanation: "Promise.all() follows a fail-fast behavior. If any promise rejects, the entire Promise.all() immediately rejects with that error, ignoring the results of other promises. Use Promise.allSettled() if you want results from all promises regardless.",
    difficulty: "MEDIUM",
    category: "JavaScript",
    solveCount: 13400,
    attemptCount: 19600,
  },
  {
    id: "q_25",
    title: "Python Generator Functions",
    slug: "python-generators",
    question: "What is the key difference between 'return' and 'yield' in Python?",
    options: [
      "yield is faster than return",
      "yield pauses the function and can be resumed, return terminates it",
      "return can be used multiple times, yield cannot",
      "They are identical in behavior"
    ],
    correctAnswer: 1,
    explanation: "yield pauses function execution and produces a value. The function state is preserved and can be resumed from where it left off. return terminates the function entirely. Functions with yield become generators that produce values lazily.",
    difficulty: "MEDIUM",
    category: "Python",
    solveCount: 10900,
    attemptCount: 16500,
  },
  {
    id: "q_26",
    title: "Linked List vs Array",
    slug: "linked-list-vs-array",
    question: "What is the time complexity of inserting an element at the beginning of a linked list vs an array?",
    options: [
      "Both O(1)",
      "Linked list O(1), Array O(n)",
      "Linked list O(n), Array O(1)",
      "Both O(n)"
    ],
    correctAnswer: 1,
    explanation: "Inserting at the beginning of a linked list is O(1) — just create a new node and point it to the old head. For an array, it's O(n) because every existing element must be shifted one position to the right to make room.",
    difficulty: "EASY",
    category: "Data Structures",
    solveCount: 21800,
    attemptCount: 25400,
  },
  {
    id: "q_27",
    title: "React State Batching",
    slug: "react-state-batching",
    question: "In React 18, how many re-renders does this code cause?\n\nfunction handleClick() {\n  setCount(c => c + 1);\n  setFlag(f => !f);\n  setName('updated');\n}",
    codeSnippet: "function handleClick() {\n  setCount(c => c + 1);\n  setFlag(f => !f);\n  setName('updated');\n}",
    options: [
      "3 re-renders",
      "2 re-renders",
      "1 re-render (batched)",
      "0 re-renders"
    ],
    correctAnswer: 2,
    explanation: "React 18 introduced automatic batching for all state updates, including those in setTimeout, promises, and event handlers. All three setState calls are batched into a single re-render for better performance.",
    difficulty: "MEDIUM",
    category: "React",
    solveCount: 9200,
    attemptCount: 15800,
  },
  {
    id: "q_28",
    title: "Database Normalization",
    slug: "database-normalization",
    question: "What does Third Normal Form (3NF) eliminate?",
    options: [
      "Duplicate tables",
      "All NULL values",
      "Transitive dependencies",
      "Foreign keys"
    ],
    correctAnswer: 2,
    explanation: "3NF eliminates transitive dependencies — when a non-key column depends on another non-key column rather than on the primary key. For example, if a table has (student_id, department_id, department_name), the department_name depends on department_id, not on student_id. This should be split into separate tables.",
    difficulty: "HARD",
    category: "Databases",
    solveCount: 5100,
    attemptCount: 12400,
  },
  {
    id: "q_29",
    title: "TypeScript Type Guards",
    slug: "typescript-type-guards",
    question: "Which of the following is a valid type guard in TypeScript?",
    codeSnippet: "function isString(value: unknown): value is string {\n  return typeof value === 'string';\n}",
    options: [
      "value as string",
      "value is string (return type annotation)",
      "typeof value",
      "<string>value"
    ],
    correctAnswer: 1,
    explanation: "A type guard is a function whose return type is a 'type predicate' (parameter is Type). When the function returns true, TypeScript narrows the type within the conditional block. 'value as string' and '<string>value' are type assertions, not guards.",
    difficulty: "HARD",
    category: "TypeScript",
    solveCount: 6200,
    attemptCount: 13100,
  },
  {
    id: "q_30",
    title: "Docker Compose",
    slug: "docker-compose",
    question: "What is the purpose of 'depends_on' in a Docker Compose file?",
    options: [
      "It ensures the dependent service is healthy before starting",
      "It controls the startup order of services",
      "It links container networks automatically",
      "It shares volumes between services"
    ],
    correctAnswer: 1,
    explanation: "depends_on controls the order in which services are started — but it does NOT wait for the service to be 'ready' or 'healthy'. It only ensures the container has started. For health checks, you need to combine depends_on with the 'condition: service_healthy' option.",
    difficulty: "MEDIUM",
    category: "DevOps",
    solveCount: 7800,
    attemptCount: 13900,
  },
  {
    id: "q_31",
    title: "Load Balancer Algorithms",
    slug: "load-balancer-algorithms",
    question: "Which load balancing algorithm sends each new request to the next server in rotation?",
    options: [
      "Least Connections",
      "Round Robin",
      "Random",
      "IP Hash"
    ],
    correctAnswer: 1,
    explanation: "Round Robin distributes requests sequentially across servers in a circular order: Server 1, Server 2, Server 3, then back to Server 1. It's simple and works well when servers have similar capacity. Weighted Round Robin adds server capacity awareness.",
    difficulty: "EASY",
    category: "System Design",
    solveCount: 18600,
    attemptCount: 22900,
  },
  {
    id: "q_32",
    title: "JavaScript 'this' Keyword",
    slug: "js-this-keyword",
    question: "What does 'this' refer to inside an arrow function?",
    codeSnippet: "const obj = {\n  name: 'Alice',\n  greet: () => {\n    console.log(this.name);\n  }\n};",
    options: [
      "The object that owns the method (obj)",
      "The global object or undefined (lexical scope)",
      "null",
      "The arrow function itself"
    ],
    correctAnswer: 1,
    explanation: "Arrow functions don't have their own 'this'. They inherit 'this' from the enclosing lexical scope (where they were defined). In this case, it's the global scope (or undefined in strict mode), not the obj — a common gotcha.",
    difficulty: "MEDIUM",
    category: "JavaScript",
    solveCount: 11800,
    attemptCount: 18300,
  },
  {
    id: "q_33",
    title: "Python Dictionary Comprehension",
    slug: "python-dict-comprehension",
    question: "What is the output?\n\nresult = {x: x**2 for x in range(4)}\nprint(result)",
    codeSnippet: "result = {x: x**2 for x in range(4)}\nprint(result)",
    options: [
      "{1: 1, 2: 4, 3: 9}",
      "{0: 0, 1: 1, 2: 4, 3: 9}",
      "[0, 1, 4, 9]",
      "Error"
    ],
    correctAnswer: 1,
    explanation: "range(4) produces 0, 1, 2, 3. The dict comprehension maps each x to x**2, creating {0: 0, 1: 1, 2: 4, 3: 9}. Note that range starts from 0 by default.",
    difficulty: "EASY",
    category: "Python",
    solveCount: 20100,
    attemptCount: 24300,
  },
  {
    id: "q_34",
    title: "Binary Search",
    slug: "binary-search",
    question: "How many comparisons does binary search need in the worst case to find an element in a sorted array of 1,000,000 elements?",
    options: [
      "1,000,000",
      "About 20",
      "500,000",
      "About 100"
    ],
    correctAnswer: 1,
    explanation: "Binary search halves the search space each step: log₂(1,000,000) ≈ 19.93, so about 20 comparisons. This is why O(log n) is so powerful — even for a million elements, you need at most 20 checks.",
    difficulty: "EASY",
    category: "Data Structures",
    solveCount: 19400,
    attemptCount: 23800,
  },
  {
    id: "q_35",
    title: "React Context vs Redux",
    slug: "react-context-vs-redux",
    question: "What is a key drawback of using React Context for frequently updating global state?",
    options: [
      "Context doesn't work with TypeScript",
      "Context causes all consumers to re-render on any value change",
      "Context is slower than localStorage",
      "Context can only hold string values"
    ],
    correctAnswer: 1,
    explanation: "When a Context value changes, ALL components consuming that context re-render — even if they only use a small part of the value. Libraries like Redux or Zustand solve this with selectors that allow fine-grained subscriptions.",
    difficulty: "MEDIUM",
    category: "React",
    solveCount: 8600,
    attemptCount: 14700,
  },
  {
    id: "q_36",
    title: "ACID Properties",
    slug: "acid-properties",
    question: "In database transactions, what does the 'I' in ACID stand for?",
    options: [
      "Integrity",
      "Isolation",
      "Immutability",
      "Indexing"
    ],
    correctAnswer: 1,
    explanation: "ACID stands for Atomicity, Consistency, Isolation, Durability. Isolation ensures that concurrent transactions don't interfere with each other — each transaction appears to run in isolation, even when multiple transactions execute simultaneously.",
    difficulty: "EASY",
    category: "Databases",
    solveCount: 22600,
    attemptCount: 26800,
  },
  {
    id: "q_37",
    title: "CSS Grid Layout",
    slug: "css-grid-layout",
    question: "What does 'grid-template-columns: repeat(auto-fit, minmax(250px, 1fr))' achieve?",
    options: [
      "Creates exactly 3 columns of 250px each",
      "A responsive grid that auto-adjusts columns to fit the container, each at least 250px wide",
      "Makes all columns exactly 1fr",
      "Hides columns smaller than 250px"
    ],
    correctAnswer: 1,
    explanation: "auto-fit fills the row with as many columns as possible. minmax(250px, 1fr) ensures each column is at least 250px but can grow to fill remaining space. This creates a fully responsive grid without media queries.",
    difficulty: "MEDIUM",
    category: "CSS",
    solveCount: 9800,
    attemptCount: 15600,
  },
  {
    id: "q_38",
    title: "Git Stash",
    slug: "git-stash",
    question: "What does 'git stash' do?",
    options: [
      "Permanently deletes uncommitted changes",
      "Temporarily saves uncommitted changes and reverts to a clean working directory",
      "Creates a new branch with current changes",
      "Pushes changes to remote without committing"
    ],
    correctAnswer: 1,
    explanation: "git stash saves your uncommitted changes (both staged and unstaged) to a stack and restores your working directory to match HEAD. You can later apply stashed changes with 'git stash pop' or 'git stash apply'.",
    difficulty: "EASY",
    category: "Git",
    solveCount: 21200,
    attemptCount: 25100,
  },
  {
    id: "q_39",
    title: "Microservices Communication",
    slug: "microservices-communication",
    question: "Which communication pattern is best for loose coupling between microservices?",
    options: [
      "Synchronous REST calls",
      "Direct database sharing",
      "Asynchronous message queues",
      "Shared in-memory cache"
    ],
    correctAnswer: 2,
    explanation: "Asynchronous message queues (like RabbitMQ or Kafka) provide the loosest coupling — services don't need to know about each other, and they can operate independently. The producer publishes a message and doesn't wait for a response.",
    difficulty: "MEDIUM",
    category: "System Design",
    solveCount: 8400,
    attemptCount: 14900,
  },
  {
    id: "q_40",
    title: "Deadlock Conditions",
    slug: "deadlock-conditions",
    question: "How many conditions must hold simultaneously for a deadlock to occur?",
    options: [
      "2",
      "3",
      "4",
      "5"
    ],
    correctAnswer: 2,
    explanation: "Deadlock requires all four Coffman conditions simultaneously: (1) Mutual Exclusion, (2) Hold and Wait, (3) No Preemption, (4) Circular Wait. Breaking any one of these conditions prevents deadlock.",
    difficulty: "HARD",
    category: "Concurrency",
    solveCount: 4500,
    attemptCount: 11200,
  },
  {
    id: "q_41",
    title: "JavaScript WeakMap",
    slug: "js-weakmap",
    question: "What is the main difference between Map and WeakMap in JavaScript?",
    options: [
      "WeakMap is faster",
      "WeakMap keys must be objects and are weakly referenced (garbage-collectible)",
      "WeakMap can only hold numbers",
      "WeakMap has a size property"
    ],
    correctAnswer: 1,
    explanation: "WeakMap keys must be objects (not primitives) and are held as weak references. If no other reference to the key object exists, it can be garbage collected along with its value. WeakMaps are not iterable and have no size property.",
    difficulty: "HARD",
    category: "JavaScript",
    solveCount: 5300,
    attemptCount: 12600,
  },
  {
    id: "q_42",
    title: "Python GIL",
    slug: "python-gil",
    question: "What does Python's Global Interpreter Lock (GIL) prevent?",
    options: [
      "Multiple processes from running",
      "Multiple threads from executing Python bytecode simultaneously",
      "Importing external modules",
      "Using more than 4GB of RAM"
    ],
    correctAnswer: 1,
    explanation: "The GIL is a mutex that allows only one thread to execute Python bytecode at a time, even on multi-core CPUs. This simplifies memory management but limits CPU-bound multithreading. Use multiprocessing or async I/O to work around it.",
    difficulty: "HARD",
    category: "Python",
    solveCount: 4800,
    attemptCount: 11900,
  },
  {
    id: "q_43",
    title: "Heap Data Structure",
    slug: "heap-data-structure",
    question: "What is the time complexity of extracting the minimum element from a min-heap?",
    options: [
      "O(1)",
      "O(log n)",
      "O(n)",
      "O(n log n)"
    ],
    correctAnswer: 1,
    explanation: "Finding the minimum is O(1) since it's always at the root, but extracting (removing) it requires re-heapifying — moving the last element to the root and sifting it down. This takes O(log n) due to the tree height.",
    difficulty: "MEDIUM",
    category: "Data Structures",
    solveCount: 10200,
    attemptCount: 16800,
  },
  {
    id: "q_44",
    title: "React Server Components",
    slug: "react-server-components",
    question: "Which of the following can a React Server Component NOT do?",
    options: [
      "Fetch data directly from a database",
      "Use useState or useEffect hooks",
      "Render HTML on the server",
      "Import server-only libraries"
    ],
    correctAnswer: 1,
    explanation: "React Server Components run only on the server and cannot use client-side hooks like useState, useEffect, or event handlers. They can directly access databases, use server-only code, and send rendered HTML to the client with zero JavaScript bundle cost.",
    difficulty: "MEDIUM",
    category: "React",
    solveCount: 7900,
    attemptCount: 13500,
  },
  {
    id: "q_45",
    title: "OAuth 2.0 Flows",
    slug: "oauth-flows",
    question: "Which OAuth 2.0 flow is recommended for single-page applications (SPAs)?",
    options: [
      "Client Credentials Grant",
      "Authorization Code with PKCE",
      "Implicit Grant",
      "Resource Owner Password Grant"
    ],
    correctAnswer: 1,
    explanation: "Authorization Code with PKCE (Proof Key for Code Exchange) is the recommended flow for SPAs. The Implicit Grant was previously used but is now discouraged due to token exposure in the URL. PKCE adds a code verifier/challenge to prevent authorization code interception.",
    difficulty: "HARD",
    category: "Web Development",
    solveCount: 4900,
    attemptCount: 12300,
  },
  {
    id: "q_46",
    title: "CSS Position Property",
    slug: "css-position",
    question: "What is the difference between 'position: absolute' and 'position: fixed'?",
    options: [
      "They are identical",
      "Absolute is relative to the nearest positioned ancestor, fixed is relative to the viewport",
      "Fixed is relative to the parent, absolute is relative to the viewport",
      "Absolute doesn't work inside flexbox"
    ],
    correctAnswer: 1,
    explanation: "position: absolute positions an element relative to its nearest positioned (non-static) ancestor. position: fixed positions relative to the viewport — it stays in place when scrolling. Both remove the element from normal document flow.",
    difficulty: "EASY",
    category: "CSS",
    solveCount: 24100,
    attemptCount: 28300,
  },
  {
    id: "q_47",
    title: "Consistent Hashing",
    slug: "consistent-hashing",
    question: "What problem does consistent hashing solve in distributed systems?",
    options: [
      "Encrypting data at rest",
      "Minimizing key remapping when nodes are added or removed",
      "Sorting data across nodes",
      "Compressing network packets"
    ],
    correctAnswer: 1,
    explanation: "Traditional hashing (hash % n) remaps almost all keys when n changes. Consistent hashing arranges servers on a ring — when a server is added/removed, only keys in that segment remap. This is critical for distributed caches and databases.",
    difficulty: "HARD",
    category: "System Design",
    solveCount: 3900,
    attemptCount: 10800,
  },
  {
    id: "q_48",
    title: "CI/CD Pipelines",
    slug: "ci-cd-pipelines",
    question: "What is the difference between Continuous Delivery and Continuous Deployment?",
    options: [
      "They are the same thing",
      "Continuous Delivery requires manual approval to deploy to production, Continuous Deployment is fully automated",
      "Continuous Deployment only runs tests, Continuous Delivery also builds",
      "Continuous Delivery doesn't use version control"
    ],
    correctAnswer: 1,
    explanation: "Continuous Delivery means code is always in a deployable state and can be released to production with a manual approval step. Continuous Deployment goes further — every change that passes all tests is automatically deployed to production with no human intervention.",
    difficulty: "MEDIUM",
    category: "DevOps",
    solveCount: 9100,
    attemptCount: 14600,
  },
  {
    id: "q_49",
    title: "JavaScript Spread vs Rest",
    slug: "js-spread-rest",
    question: "What is the output?\n\nconst [first, ...rest] = [1, 2, 3, 4, 5];\nconsole.log(rest);",
    codeSnippet: "const [first, ...rest] = [1, 2, 3, 4, 5];\nconsole.log(rest);",
    options: [
      "[1]",
      "[2, 3, 4, 5]",
      "[1, 2, 3, 4, 5]",
      "5"
    ],
    correctAnswer: 1,
    explanation: "The rest syntax (...rest) in destructuring collects the remaining elements into a new array. 'first' gets 1, and 'rest' collects everything else: [2, 3, 4, 5]. The spread operator looks identical but is used in a different context (expanding, not collecting).",
    difficulty: "EASY",
    category: "JavaScript",
    solveCount: 20800,
    attemptCount: 24900,
  },
  {
    id: "q_50",
    title: "Python Asyncio",
    slug: "python-asyncio",
    question: "What keyword is used to pause execution inside an async function until a coroutine completes?",
    options: [
      "yield",
      "wait",
      "await",
      "pause"
    ],
    correctAnswer: 2,
    explanation: "'await' suspends the execution of the async function until the awaited coroutine completes and returns a result. It can only be used inside functions defined with 'async def'. While 'yield' is used in generators, 'await' is specifically for async/await concurrency.",
    difficulty: "EASY",
    category: "Python",
    solveCount: 18900,
    attemptCount: 23200,
  },
];
